function out1 = objfunction(in1)
%OBJFUNCTION
%    OUT1 = OBJFUNCTION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Nov-2023 17:00:27

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
out1 = x1.*conj(x1).^2+x2.*conj(x2).^2+x3.*conj(x3).^2+x4.*conj(x4).^2+x5.*conj(x5).^2+x6.*conj(x6).^2+x7.*conj(x7).^2+x8.*conj(x8).^2+x9.*conj(x9).^2+x10.*conj(x10).^2;
